#!/bin/bash

# Switch to _style directory, i.e. where the "apply" script lies
cd $(dirname $0)

if [[ ! -e "../_config.yml" ]]; then
    echo "The parent directory of where 'apply' lives does not seem to be a Jekyll blog"
    echo "Aborting..."
    exit
fi

echo "Symlinking common files into blog..."
for file in $(git ls-files | grep --invert-match "apply"); do
    target="../$file"
    target_dir=$(dirname $target)

    if [[ ! -d $target_dir ]]; then
        echo "$target_dir does not exist, creating.."
        mkdir -p $target_dir
    fi

    [[ -e $target && ! -s $target ]] &&
        abort "$target exists and is not a symlink"

    [[ -e $target && -s $target ]] &&
        echo "$file already symlinked to $target"

    if [[ ! -e $target ]]; then
        echo "Symlinking $file to $target"
        ln -s "../_style/$file" $target
    fi
done
